name: Generate README with Hype
on: [pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.22.x"

    - name: Install hype
      run: go install github.com/gopherguides/hype/cmd/hype@latest

    - name: Run hype
      run: pushd .hype;hype export -format=markdown -f module.md > ../README.md;popd

    - name: Commit README back to the repo
      run: |-
        git config --global user.email "hype@gopherguides.com"
        git config --global user.name "hype"
        git diff --quiet || (git add README.md && git commit -m "Updated README")
        git push
